# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
group=de.cech12.coppershears
mod_version=2.0.0.1
mod_name=ColorBlindness Client
mod_author=Cech12
mod_id=colorblindnessclient
mod_license=The MIT License (MIT)
mod_url=https://github.com/cech12/ColorBlindnessClient
mod_issue_tracker=https://github.com/cech12/ColorBlindnessClient/issues
description=This client-side mod adds key bindings to enable color blindness effects for each variant.

# Common
java_version=25
minecraft_version=26.1
minecraft_version_range=[26.1, 27)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.144.0+26.1
fabric_loader_version=0.18.4

# Forge, see https://files.minecraftforge.net/net/minecraftforge/forge/ for new versions
net.minecraftforge.gradle.merge-source-sets=true
forge_version=62.0.3
forge_loader_version_range=[62,)

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.0.5-beta
neoforge_loader_version_range=[1,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
